### ISSUE TITLE
Missing file "Wheel.material"

### ISSUE THREAD

**Issue by chiu0602** [Janorico/Vehicle#1]
I cannot load some resources due to missing a file:
res://Scenes/Vehicles/Wheel.material

After adding the file with some .material file online, it got other png file missing.

What files should I put into the source such that I can run the game? Thanks!

**Comment by aliaslion** [comment]
Sorry for the really late answer. I have created a commit which added the ``wheel.material`` file (see above). I hope this fixes the issue, but I will double-check everything.

**Comment by aliaslion** [comment]
Found the problem, ``*.material`` and ``*.import`` files were excluded in ``.git/info/exclude``. I fixed and cloned it into a separate folder and it worked for me. Please notify me, if it doesn't work for you, otherwise close the issue. Sorry again for the late response.

Janosch Lion

**Comment by chiu0602** [comment]
@Janorico Thank your very much for your code, I have learned a lot from it!

**Comment by aliaslion** [comment]
@chiu0602 Thanks back! It's always nice if someone likes/appreciates your work :)!
